---
language: node_js
node_js:
  - "4"

cache:
  yarn: true
  directories:
    - $HOME/.yarn-cache

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME

install:
  - yarn install --no-lockfile

script:
  - yarn test
